#!/bin/sh
set -e
echo 'Installing python3 dependencies...'
pip3 install -r /usr/share/stoneflashtool/requirements.txt
echo 'Setting up service...'
#deb-systemd-helper debian-installed stoneflashtool.service || true
#deb-systemd-helper enable stoneflashtool.service || true
#deb-systemd-helper update-state stoneflashtool.service
